USE `LinkedInScrape`;

START TRANSACTION;
INSERT INTO `Skills` (Skill) VALUES ('Python');
INSERT INTO `Skills` (Skill) VALUES ('R');
INSERT INTO `Skills` (Skill) VALUES ('SQL');
INSERT INTO `Skills` (Skill) VALUES ('machine learning');
INSERT INTO `Skills` (Skill) VALUES ('TensorFlow');
INSERT INTO `Skills` (Skill) VALUES ('PyTorch');
INSERT INTO `Skills` (Skill) VALUES ('scikit-learn');
INSERT INTO `Skills` (Skill) VALUES ('AWS');
INSERT INTO `Skills` (Skill) VALUES ('Azure');
INSERT INTO `Skills` (Skill) VALUES ('MLOps');
INSERT INTO `Skills` (Skill) VALUES ('AI');
INSERT INTO `Skills` (Skill) VALUES ('Natural Language Processing');
INSERT INTO `Skills` (Skill) VALUES ('NLP');
INSERT INTO `Skills` (Skill) VALUES ('numpy');
INSERT INTO `Skills` (Skill) VALUES ('scipy');
INSERT INTO `Skills` (Skill) VALUES ('Spark');
INSERT INTO `Skills` (Skill) VALUES ('Large Language Model');
INSERT INTO `Skills` (Skill) VALUES ('Docker');
INSERT INTO `Skills` (Skill) VALUES ('PostgreSQL');
INSERT INTO `Skills` (Skill) VALUES ('MySQL');
INSERT INTO `Skills` (Skill) VALUES ('CI/CD');
INSERT INTO `Skills` (Skill) VALUES ('Agile');
INSERT INTO `Skills` (Skill) VALUES ('Github');
INSERT INTO `Skills` (Skill) VALUES ('Gitlab');
INSERT INTO `Skills` (Skill) VALUES ('TypeScript');
INSERT INTO `Skills` (Skill) VALUES ('React');
INSERT INTO `Skills` (Skill) VALUES ('Power BI');
INSERT INTO `Skills` (Skill) VALUES ('Tableau');
INSERT INTO `Skills` (Skill) VALUES ('C');
INSERT INTO `Skills` (Skill) VALUES ('C++');
INSERT INTO `Skills` (Skill) VALUES ('C#');
INSERT INTO `Skills` (Skill) VALUES ('Web Development');
INSERT INTO `Skills` (Skill) VALUES ('ASP.NET');
INSERT INTO `Skills` (Skill) VALUES ('CSS');
INSERT INTO `Skills` (Skill) VALUES ('HTML');
INSERT INTO `Skills` (Skill) VALUES ('HTML5');
INSERT INTO `Skills` (Skill) VALUES ('ML');
INSERT INTO `Skills` (Skill) VALUES ('Degree');
INSERT INTO `Skills` (Skill) VALUES ('Masters');
COMMIT;
