USE `LinkedInScrape`;

START TRANSACTION;
INSERT INTO `Skills` (Skill) VALUES ('Python');
INSERT INTO `Skills` (Skill) VALUES ('R');
INSERT INTO `Skills` (Skill) VALUES ('SQL');
INSERT INTO `Skills` (Skill) VALUES ('Excel');
INSERT INTO `Skills` (Skill) VALUES ('BI');
INSERT INTO `Skills` (Skill) VALUES ('Pandas');
INSERT INTO `Skills` (Skill) VALUES ('ambitious');
INSERT INTO `Skills` (Skill) VALUES ('problem solver');
INSERT INTO `Skills` (Skill) VALUES ('LLM');
INSERT INTO `Skills` (Skill) VALUES ('Django');
INSERT INTO `Skills` (Skill) VALUES ('Innovation');
INSERT INTO `Skills` (Skill) VALUES ('data analysis');
INSERT INTO `Skills` (Skill) VALUES ('data visualisation');
INSERT INTO `Skills` (Skill) VALUES ('Collaboration');
INSERT INTO `Skills` (Skill) VALUES ('problem solving skills');
INSERT INTO `Skills` (Skill) VALUES ('Passion');
INSERT INTO `Skills` (Skill) VALUES ('willing to travel');
INSERT INTO `Skills` (Skill) VALUES ('relational databases');
INSERT INTO `Skills` (Skill) VALUES ('Analytical');
INSERT INTO `Skills` (Skill) VALUES ('Matplotlib');
INSERT INTO `Skills` (Skill) VALUES ('Scikit-learn');
INSERT INTO `Skills` (Skill) VALUES ('NumPy');
INSERT INTO `Skills` (Skill) VALUES ('Machine Learning');
INSERT INTO `Skills` (Skill) VALUES ('TensorFlow');
INSERT INTO `Skills` (Skill) VALUES ('PyTorch');
INSERT INTO `Skills` (Skill) VALUES ('scikit-learn');
INSERT INTO `Skills` (Skill) VALUES ('AWS');
INSERT INTO `Skills` (Skill) VALUES ('Azure');
INSERT INTO `Skills` (Skill) VALUES ('MLOps');
INSERT INTO `Skills` (Skill) VALUES ('AI');
INSERT INTO `Skills` (Skill) VALUES ('Natural Language Processing');
INSERT INTO `Skills` (Skill) VALUES ('NLP');
INSERT INTO `Skills` (Skill) VALUES ('numpy');
INSERT INTO `Skills` (Skill) VALUES ('scipy');
INSERT INTO `Skills` (Skill) VALUES ('Spark');
INSERT INTO `Skills` (Skill) VALUES ('Large Language Model');
INSERT INTO `Skills` (Skill) VALUES ('Docker');
INSERT INTO `Skills` (Skill) VALUES ('PostgreSQL');
INSERT INTO `Skills` (Skill) VALUES ('MySQL');
INSERT INTO `Skills` (Skill) VALUES ('CI/CD');
INSERT INTO `Skills` (Skill) VALUES ('Agile');
INSERT INTO `Skills` (Skill) VALUES ('Github');
INSERT INTO `Skills` (Skill) VALUES ('Gitlab');
INSERT INTO `Skills` (Skill) VALUES ('TypeScript');
INSERT INTO `Skills` (Skill) VALUES ('React');
INSERT INTO `Skills` (Skill) VALUES ('Power BI');
INSERT INTO `Skills` (Skill) VALUES ('Tableau');
INSERT INTO `Skills` (Skill) VALUES ('C');
INSERT INTO `Skills` (Skill) VALUES ('C++');
INSERT INTO `Skills` (Skill) VALUES ('C#');
INSERT INTO `Skills` (Skill) VALUES ('Web Development');
INSERT INTO `Skills` (Skill) VALUES ('ASP.NET');
INSERT INTO `Skills` (Skill) VALUES ('CSS');
INSERT INTO `Skills` (Skill) VALUES ('HTML');
INSERT INTO `Skills` (Skill) VALUES ('HTML5');
INSERT INTO `Skills` (Skill) VALUES ('ML');
INSERT INTO `Skills` (Skill) VALUES ('Degree');
INSERT INTO `Skills` (Skill) VALUES ('Masters');
COMMIT;
